GeoInfo:
    data:
        city: "evere"
        country: "bel"
        region: "bru"
    schemaVersion: 1
lol-audio:
    data:
        masterSoundEnabled: false
        masterVolume: 2
    schemaVersion: 5
lol-clash:
    data:
        simpleStateFlagIds:
        - "registration_open_tournament_3522"
        - "registration_open_tournament_3661"
        - "lock_in_open_tournament_3661_phase_3781"
        - "lock_in_open_tournament_3802_phase_3922"
        - "registration_open_tournament_3681"
        - "lock_in_open_tournament_3522_phase_3642"
        - "registration_open_tournament_3542"
        - "registration_open_tournament_3821"
        - "lock_in_open_tournament_3542_phase_3662"
        - "registration_open_tournament_3822"
        - "lock_in_open_tournament_3681_phase_3801"
        - "registration_open_tournament_3701"
        - "registration_open_tournament_3761"
        - "lock_in_open_tournament_3761_phase_3881"
        - "registration_open_tournament_3781"
        - "lock_in_open_tournament_3781_phase_3901"
        - "registration_open_tournament_3801"
        - "lock_in_open_tournament_3821_phase_3941"
        - "lock_in_open_tournament_3801_phase_3921"
        - "registration_open_tournament_3782"
        - "registration_open_tournament_3841"
        - "lock_in_open_tournament_3782_phase_3902"
        - "registration_open_tournament_3783"
        - "lock_in_open_tournament_3783_phase_3903"
        - "lock_in_open_tournament_3822_phase_3942"
    schemaVersion: 1
lol-home:
    data:
        useTFTOverride: false
    schemaVersion: 0
lol-parties:
    data:
        permanentHideAutofillModal: true
    schemaVersion: 1
lol-premade-voice:
    data:
        currentCaptureDeviceHandle: "Default System Device"
        inputVolume: 50
        vadSensitivity: 65
    schemaVersion: 1
lol-replays:
    data:
        dontShowEogUsageTip: true
    schemaVersion: 1
lol-user-experience:
    data:
        lastKnownMachineSpec: 5
        potatoModeEnabled: true
        unloadLeagueClientUx: "always"
    schemaVersion: 3
video:
    data:
        ZoomScale: 0.800000
    schemaVersion: 1
