install:
    crash_reporting:
        enabled: true
        type: "crashpad"
    game-settings:
        accountId: 2873841588307648
        modified: false
        timestamp: 1640893876401
    gameflow-patcher-lock: null
    gameflow-process-info: null
    gameflow-spectate-reconnect-info: null
    globals:
        locale: "en_GB"
        region: "EUW"
    lcu-settings:
        accountId: 2873841588307648
        modified: false
        timestamp: 1640823322039
    npe-splash:
        enableNewPlayerSplash: false
    patcher:
        client_migrated: true
        client_patcher_available: true
        client_patcher_migrated_time: "2021-12-09T17:04:05Z"
        game_migrated: true
        game_patcher_available: true
        game_patcher_migrated_time: "2021-12-09T17:04:05Z"
        locales:
        - "en_GB"
        toggles:
            new_client_patcher: 0
            new_game_patcher: 0
    perks-settings:
        accountId: 2873841588307648
        modified: false
        timestamp: 1640890763755
    riotclient-upgrade:
        seq-success-count: 187
        success-count: 187
    rso-auth:
        install-identifier: "0858dc1c8d206b43b1fa6de177918e9c"
    telemetry:
        fresh_installation: true
        installation_id: "A760xw=="
