page-settings:
    data:
        pages: []
        perShardPerkBooks:
            euw1:
                currentPageId: 200373893
                pages:
                -   autoModifiedSelections: []
                    current: true
                    id: 200373893
                    isActive: false
                    isDeletable: true
                    isEditable: true
                    isValid: true
                    lastModified: 1651923918780
                    name: "Zoomies !!"
                    order: 0
                    primaryStyleId: 8200
                    selectedPerkIds:
                    - 8214
                    - 8224
                    - 8210
                    - 8237
                    - 8451
                    - 8401
                    - 5008
                    - 5008
                    - 5002
                    subStyleId: 8400
        settings:
            gameplayPatchVersionSeen: "11.23"
            gameplayUpdatedPerksSeen: []
            gridModeEnabled: false
            showLongDescriptions: false
            showPresetPages: true
    schemaVersion: 5
